# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(1000, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/assets/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        TabWidget.setWindowIcon(icon)
        TabWidget.setStyleSheet("* {\n"
"font: 10pt \"Microsoft YaHei UI\";\n"
"}\n"
"QToolButton {\n"
"background:transparent;\n"
"}\n"
"QLabel#lblResFailIcon {\n"
"background-color:rgb(255, 99, 71);\n"
"}\n"
"QLabel#lblResWarnIcon {\n"
"background-color:rgb(255, 215, 0);\n"
"}\n"
"QLabel#lblResUndefinedIcon {\n"
"background-color:rgb(0, 206, 209);\n"
"}")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.gBoxResList = QtWidgets.QGroupBox(self.tabMain)
        self.gBoxResList.setGeometry(QtCore.QRect(20, 190, 371, 461))
        self.gBoxResList.setObjectName("gBoxResList")
        self.tableResList = QtWidgets.QTableWidget(self.gBoxResList)
        self.tableResList.setGeometry(QtCore.QRect(15, 25, 341, 401))
        self.tableResList.setColumnCount(6)
        self.tableResList.setObjectName("tableResList")
        self.tableResList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableResList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResList.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gBoxResList)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 420, 281, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layoutResList = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layoutResList.setContentsMargins(0, 0, 0, 0)
        self.layoutResList.setObjectName("layoutResList")
        self.btnResListPass = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/assets/check_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnResListPass.setIcon(icon1)
        self.btnResListPass.setIconSize(QtCore.QSize(20, 20))
        self.btnResListPass.setObjectName("btnResListPass")
        self.layoutResList.addWidget(self.btnResListPass)
        self.lblResListPass = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblResListPass.setObjectName("lblResListPass")
        self.layoutResList.addWidget(self.lblResListPass)
        self.btnResListFail = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/assets/assets/cross_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnResListFail.setIcon(icon2)
        self.btnResListFail.setIconSize(QtCore.QSize(20, 20))
        self.btnResListFail.setObjectName("btnResListFail")
        self.layoutResList.addWidget(self.btnResListFail)
        self.lblResListFail = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblResListFail.setObjectName("lblResListFail")
        self.layoutResList.addWidget(self.lblResListFail)
        self.btnResListWarn = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/assets/assets/exclamation_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnResListWarn.setIcon(icon3)
        self.btnResListWarn.setIconSize(QtCore.QSize(20, 20))
        self.btnResListWarn.setObjectName("btnResListWarn")
        self.layoutResList.addWidget(self.btnResListWarn)
        self.lblResListWarn = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblResListWarn.setObjectName("lblResListWarn")
        self.layoutResList.addWidget(self.lblResListWarn)
        self.btnResListUndefined = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/assets/assets/question_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnResListUndefined.setIcon(icon4)
        self.btnResListUndefined.setIconSize(QtCore.QSize(20, 20))
        self.btnResListUndefined.setObjectName("btnResListUndefined")
        self.layoutResList.addWidget(self.btnResListUndefined)
        self.lblResListUndefined = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblResListUndefined.setObjectName("lblResListUndefined")
        self.layoutResList.addWidget(self.lblResListUndefined)
        self.gBoxRes = QtWidgets.QGroupBox(self.tabMain)
        self.gBoxRes.setGeometry(QtCore.QRect(400, 190, 571, 461))
        self.gBoxRes.setObjectName("gBoxRes")
        self.tableRes = QtWidgets.QTableWidget(self.gBoxRes)
        self.tableRes.setGeometry(QtCore.QRect(14, 25, 541, 401))
        self.tableRes.setObjectName("tableRes")
        self.tableRes.setColumnCount(4)
        self.tableRes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRes.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.gBoxRes)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 420, 401, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.layoutRes = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layoutRes.setContentsMargins(0, 0, 0, 0)
        self.layoutRes.setObjectName("layoutRes")
        self.lblResFailIcon = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResFailIcon.setEnabled(True)
        self.lblResFailIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.lblResFailIcon.setText("")
        self.lblResFailIcon.setObjectName("lblResFailIcon")
        self.layoutRes.addWidget(self.lblResFailIcon)
        self.lblResFail = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResFail.setObjectName("lblResFail")
        self.layoutRes.addWidget(self.lblResFail)
        self.lblResWarnIcon = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResWarnIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.lblResWarnIcon.setText("")
        self.lblResWarnIcon.setObjectName("lblResWarnIcon")
        self.layoutRes.addWidget(self.lblResWarnIcon)
        self.lblResWarn = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResWarn.setObjectName("lblResWarn")
        self.layoutRes.addWidget(self.lblResWarn)
        self.lblResUndefinedIcon = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResUndefinedIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.lblResUndefinedIcon.setText("")
        self.lblResUndefinedIcon.setObjectName("lblResUndefinedIcon")
        self.layoutRes.addWidget(self.lblResUndefinedIcon)
        self.lblResUndefined = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResUndefined.setObjectName("lblResUndefined")
        self.layoutRes.addWidget(self.lblResUndefined)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tabMain)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 10, 311, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.layoutMode = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.layoutMode.setContentsMargins(0, 0, 0, 0)
        self.layoutMode.setObjectName("layoutMode")
        self.rBtnSerial = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rBtnSerial.setObjectName("rBtnSerial")
        self.layoutMode.addWidget(self.rBtnSerial)
        self.rBtnKafka = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rBtnKafka.setObjectName("rBtnKafka")
        self.layoutMode.addWidget(self.rBtnKafka)
        self.rBtnManual = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rBtnManual.setObjectName("rBtnManual")
        self.layoutMode.addWidget(self.rBtnManual)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabMain)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 651, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutConfig = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutConfig.setContentsMargins(0, 0, 0, 0)
        self.layoutConfig.setObjectName("layoutConfig")
        self.gBoxSerial = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.gBoxSerial.setObjectName("gBoxSerial")
        self.gridLayoutWidget = QtWidgets.QWidget(self.gBoxSerial)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 24, 621, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.layoutSerial = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.layoutSerial.setContentsMargins(0, 0, 0, 0)
        self.layoutSerial.setObjectName("layoutSerial")
        self.btnSerialStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSerialStop.setObjectName("btnSerialStop")
        self.layoutSerial.addWidget(self.btnSerialStop, 2, 4, 1, 1)
        self.lblSerialFilter = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSerialFilter.setObjectName("lblSerialFilter")
        self.layoutSerial.addWidget(self.lblSerialFilter, 0, 2, 1, 1)
        self.btnSerialStart = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSerialStart.setObjectName("btnSerialStart")
        self.layoutSerial.addWidget(self.btnSerialStart, 2, 3, 1, 1)
        self.lblSerialCmd = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSerialCmd.setObjectName("lblSerialCmd")
        self.layoutSerial.addWidget(self.lblSerialCmd, 2, 0, 1, 1)
        self.btnSerialEdit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSerialEdit.setObjectName("btnSerialEdit")
        self.layoutSerial.addWidget(self.btnSerialEdit, 2, 2, 1, 1)
        self.cBoxSerialCmd = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cBoxSerialCmd.setObjectName("cBoxSerialCmd")
        self.layoutSerial.addWidget(self.cBoxSerialCmd, 2, 1, 1, 1)
        self.lblSerialPort = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSerialPort.setObjectName("lblSerialPort")
        self.layoutSerial.addWidget(self.lblSerialPort, 0, 0, 1, 1)
        self.cBoxSerialPort = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cBoxSerialPort.setObjectName("cBoxSerialPort")
        self.layoutSerial.addWidget(self.cBoxSerialPort, 0, 1, 1, 1)
        self.btnSerialClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSerialClear.setObjectName("btnSerialClear")
        self.layoutSerial.addWidget(self.btnSerialClear, 2, 5, 1, 1)
        self.editSerialFilter = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editSerialFilter.setObjectName("editSerialFilter")
        self.layoutSerial.addWidget(self.editSerialFilter, 0, 3, 1, 3)
        self.layoutConfig.addWidget(self.gBoxSerial)
        self.gBoxManual = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.gBoxManual.setObjectName("gBoxManual")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.gBoxManual)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 34, 621, 73))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.layoutManual = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.layoutManual.setContentsMargins(0, 0, 0, 0)
        self.layoutManual.setObjectName("layoutManual")
        self.btnManualStart = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnManualStart.setObjectName("btnManualStart")
        self.layoutManual.addWidget(self.btnManualStart, 2, 1, 1, 1)
        self.btnManualClear = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnManualClear.setObjectName("btnManualClear")
        self.layoutManual.addWidget(self.btnManualClear, 0, 1, 1, 1)
        self.editManual = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.editManual.setObjectName("editManual")
        self.layoutManual.addWidget(self.editManual, 0, 0, 3, 1)
        self.layoutConfig.addWidget(self.gBoxManual)
        self.gBoxKafka = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.gBoxKafka.setObjectName("gBoxKafka")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.gBoxKafka)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 24, 621, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.layoutKafka = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.layoutKafka.setContentsMargins(0, 0, 0, 0)
        self.layoutKafka.setObjectName("layoutKafka")
        self.lblKafkaServer = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblKafkaServer.setObjectName("lblKafkaServer")
        self.layoutKafka.addWidget(self.lblKafkaServer, 0, 0, 1, 1)
        self.lblKafkaTopic = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblKafkaTopic.setObjectName("lblKafkaTopic")
        self.layoutKafka.addWidget(self.lblKafkaTopic, 2, 0, 1, 1)
        self.editKafkaFilter = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.editKafkaFilter.setObjectName("editKafkaFilter")
        self.layoutKafka.addWidget(self.editKafkaFilter, 0, 4, 1, 3)
        self.cBoxKafkaServer = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cBoxKafkaServer.setObjectName("cBoxKafkaServer")
        self.layoutKafka.addWidget(self.cBoxKafkaServer, 0, 1, 1, 1)
        self.btnKafkaStart = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnKafkaStart.setObjectName("btnKafkaStart")
        self.layoutKafka.addWidget(self.btnKafkaStart, 2, 4, 1, 1)
        self.btnKafkaClear = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnKafkaClear.setObjectName("btnKafkaClear")
        self.layoutKafka.addWidget(self.btnKafkaClear, 2, 6, 1, 1)
        self.btnKafkaStop = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnKafkaStop.setObjectName("btnKafkaStop")
        self.layoutKafka.addWidget(self.btnKafkaStop, 2, 5, 1, 1)
        self.lblKafkaFilter = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblKafkaFilter.setObjectName("lblKafkaFilter")
        self.layoutKafka.addWidget(self.lblKafkaFilter, 0, 3, 1, 1)
        self.cBoxKafkaTopic = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cBoxKafkaTopic.setObjectName("cBoxKafkaTopic")
        self.layoutKafka.addWidget(self.cBoxKafkaTopic, 2, 1, 1, 2)
        self.btnKafkaEdit = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnKafkaEdit.setObjectName("btnKafkaEdit")
        self.layoutKafka.addWidget(self.btnKafkaEdit, 0, 2, 1, 1)
        self.layoutConfig.addWidget(self.gBoxKafka)
        TabWidget.addTab(self.tabMain, "")
        self.tabHint = QtWidgets.QWidget()
        self.tabHint.setObjectName("tabHint")
        TabWidget.addTab(self.tabHint, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.gBoxResList.setTitle(_translate("TabWidget", "验证结果"))
        item = self.tableResList.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "上级事件"))
        item = self.tableResList.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "本级事件"))
        item = self.tableResList.horizontalHeaderItem(2)
        item.setText(_translate("TabWidget", "别名"))
        item = self.tableResList.horizontalHeaderItem(3)
        item.setText(_translate("TabWidget", "结果"))
        self.btnResListPass.setText(_translate("TabWidget", "..."))
        self.lblResListPass.setText(_translate("TabWidget", "正常"))
        self.btnResListFail.setText(_translate("TabWidget", "..."))
        self.lblResListFail.setText(_translate("TabWidget", "异常"))
        self.btnResListWarn.setText(_translate("TabWidget", "..."))
        self.lblResListWarn.setText(_translate("TabWidget", "告警"))
        self.btnResListUndefined.setText(_translate("TabWidget", "..."))
        self.lblResListUndefined.setText(_translate("TabWidget", "未定义"))
        self.gBoxRes.setTitle(_translate("TabWidget", "一级数据"))
        item = self.tableRes.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "键"))
        item = self.tableRes.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "别名"))
        item = self.tableRes.horizontalHeaderItem(2)
        item.setText(_translate("TabWidget", "值"))
        item = self.tableRes.horizontalHeaderItem(3)
        item.setText(_translate("TabWidget", "别名"))
        self.lblResFail.setText(_translate("TabWidget", "值与正则不符"))
        self.lblResWarn.setText(_translate("TabWidget", "键有定义但未上报"))
        self.lblResUndefined.setText(_translate("TabWidget", "键有上报但未定义"))
        self.rBtnSerial.setText(_translate("TabWidget", "串口模式"))
        self.rBtnKafka.setText(_translate("TabWidget", "Kafka模式"))
        self.rBtnManual.setText(_translate("TabWidget", "手动模式"))
        self.gBoxSerial.setTitle(_translate("TabWidget", "串口配置"))
        self.btnSerialStop.setText(_translate("TabWidget", "停止"))
        self.lblSerialFilter.setText(_translate("TabWidget", "过滤词"))
        self.btnSerialStart.setText(_translate("TabWidget", "开始"))
        self.lblSerialCmd.setText(_translate("TabWidget", "执行命令"))
        self.btnSerialEdit.setText(_translate("TabWidget", "编辑"))
        self.lblSerialPort.setText(_translate("TabWidget", "端口"))
        self.btnSerialClear.setText(_translate("TabWidget", "清空"))
        self.gBoxManual.setTitle(_translate("TabWidget", "输入日志数据"))
        self.btnManualStart.setText(_translate("TabWidget", "验证"))
        self.btnManualClear.setText(_translate("TabWidget", "清空"))
        self.gBoxKafka.setTitle(_translate("TabWidget", "Kafka配置"))
        self.lblKafkaServer.setText(_translate("TabWidget", "server"))
        self.lblKafkaTopic.setText(_translate("TabWidget", "topic"))
        self.btnKafkaStart.setText(_translate("TabWidget", "开始"))
        self.btnKafkaClear.setText(_translate("TabWidget", "清空"))
        self.btnKafkaStop.setText(_translate("TabWidget", "停止"))
        self.lblKafkaFilter.setText(_translate("TabWidget", "过滤词"))
        self.btnKafkaEdit.setText(_translate("TabWidget", "编辑"))
        TabWidget.setTabText(TabWidget.indexOf(self.tabMain), _translate("TabWidget", "日志验证"))
        TabWidget.setTabText(TabWidget.indexOf(self.tabHint), _translate("TabWidget", "使用说明"))

import assets_rc
