# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 635)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 635))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 635))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/assets/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"font: 10pt \"Microsoft YaHei UI\";\n"
"}\n"
"QToolButton {\n"
"background:transparent;\n"
"}\n"
"QLabel#lblResFailIcon {\n"
"background-color:rgb(255, 99, 71);\n"
"}\n"
"QLabel#lblResWarnIcon {\n"
"background-color:rgb(255, 215, 0);\n"
"}\n"
"QLabel#lblResUndefinedIcon {\n"
"background-color:rgb(0, 206, 209);\n"
"}\n"
"QLabel#lblSerialPort,\n"
"#lblSerialCmd,\n"
"#lblSerialFilter,\n"
"#lblKafkaServer,\n"
"#lblKafkaTopic,\n"
"#lblKafkaFilter {\n"
"margin-right:5px;\n"
"max-width:60px;\n"
"}\n"
"QLabel#lblResFail {\n"
"margin-right:10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 671, 141))
        self.tabWidget.setObjectName("tabWidget")
        self.tabSerial = QtWidgets.QWidget()
        self.tabSerial.setObjectName("tabSerial")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabSerial)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 621, 85))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.layoutSerial = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.layoutSerial.setContentsMargins(0, 0, 0, 0)
        self.layoutSerial.setObjectName("layoutSerial")
        self.cBoxSerialCmd = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cBoxSerialCmd.setObjectName("cBoxSerialCmd")
        self.layoutSerial.addWidget(self.cBoxSerialCmd, 2, 1, 1, 1)
        self.btnSerialEdit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSerialEdit.setObjectName("btnSerialEdit")
        self.layoutSerial.addWidget(self.btnSerialEdit, 2, 2, 1, 1)
        self.cBoxSerialPort = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cBoxSerialPort.setObjectName("cBoxSerialPort")
        self.layoutSerial.addWidget(self.cBoxSerialPort, 0, 1, 1, 1)
        self.editSerialFilter = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editSerialFilter.setObjectName("editSerialFilter")
        self.layoutSerial.addWidget(self.editSerialFilter, 0, 4, 1, 3)
        self.btnSerialStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSerialStop.setObjectName("btnSerialStop")
        self.layoutSerial.addWidget(self.btnSerialStop, 2, 5, 1, 1)
        self.lblSerialCmd = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSerialCmd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSerialCmd.setObjectName("lblSerialCmd")
        self.layoutSerial.addWidget(self.lblSerialCmd, 2, 0, 1, 1)
        self.btnSerialClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSerialClear.setObjectName("btnSerialClear")
        self.layoutSerial.addWidget(self.btnSerialClear, 2, 6, 1, 1)
        self.lblSerialPort = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSerialPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSerialPort.setObjectName("lblSerialPort")
        self.layoutSerial.addWidget(self.lblSerialPort, 0, 0, 1, 1)
        self.btnSerialStart = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSerialStart.setObjectName("btnSerialStart")
        self.layoutSerial.addWidget(self.btnSerialStart, 2, 4, 1, 1)
        self.lblSerialFilter = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSerialFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSerialFilter.setObjectName("lblSerialFilter")
        self.layoutSerial.addWidget(self.lblSerialFilter, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tabSerial, "")
        self.tabKafka = QtWidgets.QWidget()
        self.tabKafka.setObjectName("tabKafka")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabKafka)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 621, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.layoutKafka = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.layoutKafka.setContentsMargins(0, 0, 0, 0)
        self.layoutKafka.setObjectName("layoutKafka")
        self.lblKafkaServer = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblKafkaServer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblKafkaServer.setObjectName("lblKafkaServer")
        self.layoutKafka.addWidget(self.lblKafkaServer, 0, 0, 1, 1)
        self.lblKafkaTopic = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblKafkaTopic.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblKafkaTopic.setObjectName("lblKafkaTopic")
        self.layoutKafka.addWidget(self.lblKafkaTopic, 2, 0, 1, 1)
        self.editKafkaFilter = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.editKafkaFilter.setObjectName("editKafkaFilter")
        self.layoutKafka.addWidget(self.editKafkaFilter, 0, 4, 1, 3)
        self.cBoxKafkaServer = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cBoxKafkaServer.setObjectName("cBoxKafkaServer")
        self.layoutKafka.addWidget(self.cBoxKafkaServer, 0, 1, 1, 1)
        self.btnKafkaStart = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnKafkaStart.setObjectName("btnKafkaStart")
        self.layoutKafka.addWidget(self.btnKafkaStart, 2, 4, 1, 1)
        self.btnKafkaClear = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnKafkaClear.setObjectName("btnKafkaClear")
        self.layoutKafka.addWidget(self.btnKafkaClear, 2, 6, 1, 1)
        self.btnKafkaStop = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnKafkaStop.setObjectName("btnKafkaStop")
        self.layoutKafka.addWidget(self.btnKafkaStop, 2, 5, 1, 1)
        self.lblKafkaFilter = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblKafkaFilter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblKafkaFilter.setObjectName("lblKafkaFilter")
        self.layoutKafka.addWidget(self.lblKafkaFilter, 0, 3, 1, 1)
        self.cBoxKafkaTopic = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cBoxKafkaTopic.setObjectName("cBoxKafkaTopic")
        self.layoutKafka.addWidget(self.cBoxKafkaTopic, 2, 1, 1, 2)
        self.btnKafkaEdit = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnKafkaEdit.setObjectName("btnKafkaEdit")
        self.layoutKafka.addWidget(self.btnKafkaEdit, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tabKafka, "")
        self.tabManual = QtWidgets.QWidget()
        self.tabManual.setObjectName("tabManual")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tabManual)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 621, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.layoutManual = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.layoutManual.setContentsMargins(0, 0, 0, 0)
        self.layoutManual.setObjectName("layoutManual")
        self.btnManualClear = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnManualClear.setObjectName("btnManualClear")
        self.layoutManual.addWidget(self.btnManualClear, 0, 1, 1, 1)
        self.btnManualStart = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnManualStart.setObjectName("btnManualStart")
        self.layoutManual.addWidget(self.btnManualStart, 1, 1, 1, 1)
        self.editManual = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.editManual.setObjectName("editManual")
        self.layoutManual.addWidget(self.editManual, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tabManual, "")
        self.gBoxRes = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxRes.setGeometry(QtCore.QRect(410, 170, 571, 441))
        self.gBoxRes.setObjectName("gBoxRes")
        self.tableRes = QtWidgets.QTableWidget(self.gBoxRes)
        self.tableRes.setGeometry(QtCore.QRect(14, 25, 541, 381))
        self.tableRes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableRes.setObjectName("tableRes")
        self.tableRes.setColumnCount(4)
        self.tableRes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRes.setHorizontalHeaderItem(3, item)
        self.tableRes.horizontalHeader().setDefaultSectionSize(135)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.gBoxRes)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 400, 431, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.layoutRes = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layoutRes.setContentsMargins(0, 0, 0, 0)
        self.layoutRes.setObjectName("layoutRes")
        self.lblResFailIcon = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResFailIcon.setEnabled(True)
        self.lblResFailIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.lblResFailIcon.setText("")
        self.lblResFailIcon.setObjectName("lblResFailIcon")
        self.layoutRes.addWidget(self.lblResFailIcon)
        self.lblResFail = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResFail.setObjectName("lblResFail")
        self.layoutRes.addWidget(self.lblResFail)
        self.lblResWarnIcon = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResWarnIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.lblResWarnIcon.setText("")
        self.lblResWarnIcon.setObjectName("lblResWarnIcon")
        self.layoutRes.addWidget(self.lblResWarnIcon)
        self.lblResWarn = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResWarn.setObjectName("lblResWarn")
        self.layoutRes.addWidget(self.lblResWarn)
        self.lblResUndefinedIcon = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResUndefinedIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.lblResUndefinedIcon.setText("")
        self.lblResUndefinedIcon.setObjectName("lblResUndefinedIcon")
        self.layoutRes.addWidget(self.lblResUndefinedIcon)
        self.lblResUndefined = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblResUndefined.setObjectName("lblResUndefined")
        self.layoutRes.addWidget(self.lblResUndefined)
        self.gBoxResList = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxResList.setGeometry(QtCore.QRect(20, 170, 371, 441))
        self.gBoxResList.setObjectName("gBoxResList")
        self.tableResList = QtWidgets.QTableWidget(self.gBoxResList)
        self.tableResList.setEnabled(True)
        self.tableResList.setGeometry(QtCore.QRect(15, 25, 341, 380))
        self.tableResList.setMinimumSize(QtCore.QSize(341, 380))
        self.tableResList.setMaximumSize(QtCore.QSize(341, 380))
        self.tableResList.setToolTipDuration(-3)
        self.tableResList.setLineWidth(-3)
        self.tableResList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableResList.setColumnCount(6)
        self.tableResList.setObjectName("tableResList")
        self.tableResList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableResList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableResList.setHorizontalHeaderItem(3, item)
        self.tableResList.horizontalHeader().setDefaultSectionSize(80)
        self.tableResList.horizontalHeader().setMinimumSectionSize(30)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gBoxResList)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 400, 291, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layoutResList = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layoutResList.setContentsMargins(0, 0, 0, 0)
        self.layoutResList.setObjectName("layoutResList")
        self.btnResListPass = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/assets/check_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnResListPass.setIcon(icon1)
        self.btnResListPass.setIconSize(QtCore.QSize(20, 20))
        self.btnResListPass.setObjectName("btnResListPass")
        self.layoutResList.addWidget(self.btnResListPass)
        self.lblResListPass = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblResListPass.setObjectName("lblResListPass")
        self.layoutResList.addWidget(self.lblResListPass)
        self.btnResListFail = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/assets/cross_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnResListFail.setIcon(icon2)
        self.btnResListFail.setIconSize(QtCore.QSize(20, 20))
        self.btnResListFail.setObjectName("btnResListFail")
        self.layoutResList.addWidget(self.btnResListFail)
        self.lblResListFail = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblResListFail.setObjectName("lblResListFail")
        self.layoutResList.addWidget(self.lblResListFail)
        self.btnResListWarn = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/assets/exclamation_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnResListWarn.setIcon(icon3)
        self.btnResListWarn.setIconSize(QtCore.QSize(20, 20))
        self.btnResListWarn.setObjectName("btnResListWarn")
        self.layoutResList.addWidget(self.btnResListWarn)
        self.lblResListWarn = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblResListWarn.setObjectName("lblResListWarn")
        self.layoutResList.addWidget(self.lblResListWarn)
        self.btnResListUndefined = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/assets/question_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnResListUndefined.setIcon(icon4)
        self.btnResListUndefined.setIconSize(QtCore.QSize(20, 20))
        self.btnResListUndefined.setObjectName("btnResListUndefined")
        self.layoutResList.addWidget(self.btnResListUndefined)
        self.lblResListUndefined = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblResListUndefined.setObjectName("lblResListUndefined")
        self.layoutResList.addWidget(self.lblResListUndefined)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "日志验证工具 v1.3"))
        self.btnSerialEdit.setText(_translate("MainWindow", "编辑"))
        self.btnSerialStop.setText(_translate("MainWindow", "停止"))
        self.lblSerialCmd.setText(_translate("MainWindow", "执行命令"))
        self.btnSerialClear.setText(_translate("MainWindow", "清空"))
        self.lblSerialPort.setText(_translate("MainWindow", "端口"))
        self.btnSerialStart.setText(_translate("MainWindow", "开始"))
        self.lblSerialFilter.setText(_translate("MainWindow", "过滤词"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSerial), _translate("MainWindow", "串口模式"))
        self.lblKafkaServer.setText(_translate("MainWindow", "server"))
        self.lblKafkaTopic.setText(_translate("MainWindow", "topic"))
        self.btnKafkaStart.setText(_translate("MainWindow", "开始"))
        self.btnKafkaClear.setText(_translate("MainWindow", "清空"))
        self.btnKafkaStop.setText(_translate("MainWindow", "停止"))
        self.lblKafkaFilter.setText(_translate("MainWindow", "过滤词"))
        self.btnKafkaEdit.setText(_translate("MainWindow", "编辑"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabKafka), _translate("MainWindow", "Kafka模式"))
        self.btnManualClear.setText(_translate("MainWindow", "清空"))
        self.btnManualStart.setText(_translate("MainWindow", "验证"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabManual), _translate("MainWindow", "手动模式"))
        self.gBoxRes.setTitle(_translate("MainWindow", "一级数据"))
        item = self.tableRes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "键"))
        item = self.tableRes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "别名"))
        item = self.tableRes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "值"))
        item = self.tableRes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "别名"))
        self.lblResFail.setText(_translate("MainWindow", "值与正则不符"))
        self.lblResWarn.setText(_translate("MainWindow", "键有定义但未上报"))
        self.lblResUndefined.setText(_translate("MainWindow", "键有上报但未定义"))
        self.gBoxResList.setTitle(_translate("MainWindow", "验证结果"))
        item = self.tableResList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "上级事件"))
        item = self.tableResList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "本级事件"))
        item = self.tableResList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "别名"))
        item = self.tableResList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "结果"))
        self.btnResListPass.setText(_translate("MainWindow", "..."))
        self.lblResListPass.setText(_translate("MainWindow", "正常"))
        self.btnResListFail.setText(_translate("MainWindow", "..."))
        self.lblResListFail.setText(_translate("MainWindow", "异常"))
        self.btnResListWarn.setText(_translate("MainWindow", "..."))
        self.lblResListWarn.setText(_translate("MainWindow", "告警"))
        self.btnResListUndefined.setText(_translate("MainWindow", "..."))
        self.lblResListUndefined.setText(_translate("MainWindow", "未定义"))

import assets_rc
